### ISSUE TITLE
How to check the output of Person Detection example

### ISSUE THREAD

**Issue by abhinavrawat27** [espressif/esp-tflite-micro#37]
Hi

I have build and deployed the person detection example fine with no errors. But not sure how to monitor the output.
I ran `idf.py -p /dev/ttyACM0 flash monitor` and it started uploading and then below text shows on terminal

    Executing "/home/thingtrax/.espressif/python_env/idf4.4_py3.10_env/bin/python /home/thingtrax/esp/esp-idf/tools/idf_monitor.py -p /dev/ttyACM0 -b 115200 --toolchain-prefix xtensa-esp32s3-elf- --target esp32s3 /home/thingtrax/tflite-micro-esp-examples/examples/person_detection/build/person_detection.elf -m '/home/thingtrax/.espressif/python_env/idf4.4_py3.10_env/bin/python' '/home/thingtrax/esp/esp-idf/tools/idf.py' '-p' '/dev/ttyACM0'"...
	--- idf_monitor on /dev/ttyACM0 115200 ---
	--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
	I (164) esp_image: segment 1: paddr=0007c730 vaddr=3fc91fESP-ROM:esp32s3-20210327
	Build:Mar 27 2021
	rst:0x15 (USB_UART_CHIP_RESET),boot:0x2a (SPI_FAST_FLASH_BOOT)
	Saved PC:0x403ce633
	SPIWP:0xee
	mode:DIO, clock div:1
	load:0x3fce3808,len:0x17b8
	load:0x403c9700,len:0xe64
	load:0x403cc700,len:0x2fec
	entry 0x403c9980
	I (24) boot: ESP-IDF v4.4.3 2nd stage bootloader
	I (25) boot: compile time 14:52:04
	I (25) boot: chip revision: 0
	I (26) qio_mode: Enabling default flash chip QIO
	I (32) boot.esp32s3: Boot SPI Speed : 80MHz
	I (36) boot.esp32s3: SPI Mode       : QIO
	I (41) boot.esp32s3: SPI Flash Size : 8MB
	I (46) boot: Enabling RNG early entropy source...
	I (51) boot: Partition Table:
	I (55) boot: ## Label            Usage          Type ST Offset   Length
	I (62) boot:  0 nvs              WiFi data        01 02 00009000 00006000
	I (70) boot:  1 phy_init         RF data          01 01 0000f000 00001000
	I (77) boot:  2 factory          factory app      00 00 00010000 00180000
	I (84) boot: End of partition table
	I (89) esp_image: segment 0: paddr=00010020 vaddr=3c030020 size=6c708h (444168) map
	I (164) esp_image: segment 1: paddr=0007c730 vaddr=3fc91f30 size=02a40h ( 10816) load
	I (167) esp_image: segment 2: paddr=0007f178 vaddr=40374000 size=00ea0h (  3744) load
	I (171) esp_image: segment 3: paddr=00080020 vaddr=42000020 size=2a2b4h (172724) map
	I (205) esp_image: segment 4: paddr=000aa2dc vaddr=40374ea0 size=0d090h ( 53392) load
	I (215) esp_image: segment 5: paddr=000b7374 vaddr=50000000 size=00010h (    16) load
	I (221) boot: Loaded app from partition at offset 0x10000
	I (222) boot: Disabling RNG early entropy source...
	I (236) opi psram: vendor id : 0x0d (AP)
	I (236) opi psram: dev id    : 0x02 (generation 3)
	I (236) opi psram: density   : 0x03 (64 Mbit)
	I (239) opi psram: good-die  : 0x01 (Pass)
	I (244) opi psram: Latency   : 0x01 (Fixed)
	I (249) opi psram: VCC       : 0x01 (3V)
	I (254) opi psram: SRF       : 0x01 (Fast Refresh)
	I (259) opi psram: BurstType : 0x01 (Hybrid Wrap)
	I (265) opi psram: BurstLen  : 0x01 (32 Byte)
	I (270) opi psram: Readlatency  : 0x02 (10 cycles@Fixed)
	I (276) opi psram: DriveStrength: 0x00 (1/1)
	W (281) PSRAM: DO NOT USE FOR MASS PRODUCTION! Timing parameters will be updated in future IDF version.
	I (291) spiram: Found 64MBit SPI RAM device
	I (295) spiram: SPI RAM mode: sram 80m
	I (300) spiram: PSRAM initialized, cache is in normal (1-core) mode.
	I (307) cpu_start: Pro cpu up.
	I (311) cpu_start: Starting app cpu, entry point is 0x40375384
	0x40375384: call_start_cpu1 at /home/thingtrax/esp/esp-idf/components/esp_system/port/cpu_start.c:148

	I (0) cpu_start: App cpu up.
	I (602) spiram: SPI SRAM memory test OK
	I (611) cpu_start: Pro cpu start user code
	I (611) cpu_start: cpu freq: 240000000
	I (611) cpu_start: Application information:
	I (614) cpu_start: Project name:     person_detection
	I (620) cpu_start: App version:      83bc5cc
	I (625) cpu_start: Compile time:     Apr 11 2023 14:51:58
	I (631) cpu_start: ELF file SHA256:  36939b8a6844ef87...
	I (637) cpu_start: ESP-IDF:          v4.4.3
	I (642) heap_init: Initializing. RAM available for dynamic allocation:
	I (649) heap_init: At 3FC955F0 len 00054120 (336 KiB): D/IRAM
	I (655) heap_init: At 3FCE9710 len 00005724 (21 KiB): STACK/DRAM
	I (662) heap_init: At 600FE000 len 00002000 (8 KiB): RTCRAM
	I (668) spiram: Adding pool of 8192K of external SPI memory to heap allocator
	I (676) spi_flash: detected chip: generic
	I (681) spi_flash: flash io: qio
	I (685) sleep: Configure to isolate all GPIO pins in sleep state
	I (691) sleep: Enable automatic switching of GPIO sleep configuration
	I (699) cpu_start: Starting scheduler on PRO CPU.
	I (0) cpu_start: Starting scheduler on APP CPU.
	I (745) [esp_cli]: Initialising UART on port 0
	I (20) [esp_cli]: Registering command: mem-dump
	I (745) uart: queue free spaces: 8
	I (745) [esp_cli]: Registering command: task-dump
	I (755) [esp_cli]: Registering command: cpu-dump
	I (765) [esp_cli]: Registering command: detect_image

Where does it shows the output of the person detected. Also I want to know is there a way to show output of person detection on lcd of ESP32 S3?

Thanks

**Comment by vikramdattu** [comment]
@abhinavrawat27 

Please find the description [here](https://github.com/espressif/tflite-micro-esp-examples/tree/master/examples/person_detection#using-cli-for-inferencing) for CLI inferencing on already embedded images.
To be able to use camera feed and display, do enable this in `esp_main.h` https://github.com/espressif/tflite-micro-esp-examples/tree/master/examples/person_detection#using-display
