### ISSUE TITLE
esp_nn.h File During Compilation with -D ESP_NN (TFMIC-34)

### ISSUE THREAD

**Issue by pravee625** [espressif/esp-tflite-micro#91]
When I include the -D ESP_NN flag in my platformio.ini, I encounter the following error during compilation:

Compiling .pio\build\esp-wrover-kit\libde0\tfmicro\tensorflow\lite\micro\kernels\esp_nn\add.cc.o
Compiling .pio\build\esp-wrover-kit\libde0\tfmicro\tensorflow\lite\micro\kernels\esp_nn\conv.cc.o
lib/tfmicro/tensorflow/lite/micro/kernels/esp_nn/add.cc:34:10: fatal error: esp_nn.h: No such file or directory

****************************************************************
* Looking for esp_nn.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:esp_nn.h"
* Web  > https://registry.platformio.org/search?q=header:esp_nn.h
*
****************************************************************

 #include <esp_nn.h>
          ^~~~~~~~~~
compilation terminated.
Compiling .pio\build\esp-wrover-kit\libde0\tfmicro\tensorflow\lite\micro\kernels\esp_nn\depthwise_conv.cc.o
*** [.pio\build\esp-wrover-kit\libde0\tfmicro\tensorflow\lite\micro\kernels\esp_nn\add.cc.o] Error 1
lib/tfmicro/tensorflow/lite/micro/kernels/esp_nn/conv.cc:30:10: fatal error: esp_nn.h: No such file or directory

****************************************************************
* Looking for esp_nn.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:esp_nn.h"
* Web  > https://registry.platformio.org/search?q=header:esp_nn.h
*
****************************************************************

 #include <esp_nn.h>
          ^~~~~~~~~~
compilation terminated.
*** [.pio\build\esp-wrover-kit\libde0\tfmicro\tensorflow\lite\micro\kernels\esp_nn\conv.cc.o] Error 1
lib/tfmicro/tensorflow/lite/micro/kernels/esp_nn/depthwise_conv.cc:30:10: fatal error: esp_nn.h: No such file or directory

****************************************************************
* Looking for esp_nn.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:esp_nn.h"
* Web  > https://registry.platformio.org/search?q=header:esp_nn.h
*
****************************************************************

 #include <esp_nn.h>
          ^~~~~~~~~~
compilation terminated.
*** [.pio\build\esp-wrover-kit\libde0\tfmicro\tensorflow\lite\micro\kernels\esp_nn\depthwise_conv.cc.o] Error 1
========================================================= [FAILED] Took 31.34 seconds =========================================================

 *  The terminal process "C:\Users\prave\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 

When I remove the -D ESP_NN flag from my platformio.ini, the compilation is successful.

Is the esp_nn.h file not present in the esp-tflite-micro library?
How can I properly include the ESP-NN library while compiling in PlatformIO?

I am attaching my platformio.ini file for  your reference
![image](https://github.com/user-attachments/assets/d3dc7673-cd0d-4e1f-9b6b-dc6d449ee945)

**Comment by vikramdattu** [comment]
@pravee625 is this issue still valid after https://github.com/espressif/esp-tflite-micro/issues/93 is addressed?

**Comment by pravee625** [comment]
@vikramdattu Yes, I am still unable to compile with -D ESP_NN if declared in my platformio.ini file 

if ESP_NN is declared in platformio.ini 
then esp_nn.h file is required 
https://github.com/espressif/esp-tflite-micro/blob/e63e91b37c52e8085a6af83048aafc8b0ddaf1a2/tensorflow/lite/micro/kernels/esp_nn/add.cc#L34
and I am unable to find that file in the current repo...

**Comment by vikramdattu** [comment]
Hi @pravee625 `esp-nn` is separate component and with `esp-idf`'s build system, it gets pulled in transparently as a dependency to `esp-tflite-micro`. This happens via dependency specified in `idf_component.yml`: https://github.com/espressif/esp-tflite-micro/blob/e63e91b37c52e8085a6af83048aafc8b0ddaf1a2/idf_component.yml#L10-L12

<br>
For platform.io, can you please follow [this](https://docs.platformio.org/en/latest/frameworks/espidf.html#esp-idf-components) piece of documentation? 
`esp-nn` can be cloned from [here](https://github.com/espressif/esp-nn) and you can then add it manually as per above documentation.

**Comment by pravee625** [comment]
Thanks for the help @vikramdattu. My code is working fine, and esp_nn is successfully integrated. You can close this issue as well as the other issue: https://github.com/espressif/esp-tflite-micro/issues/90. The previous issue was also caused by esp_nn optimizations not being included. Now, my inference time has decreased from 900ms to 200ms.

**Comment by vikramdattu** [comment]
Hi @pravee625 thanks for the confirmation. Closing this issue!
